import { NextResponse } from "next/server";
import { currentUser } from "@clerk/nextjs/server";
import { db } from "@/lib/dbConfig";
import { Events } from "@/lib/schema";

// Add user to DB
export async function GET() {
  try {
    const user = await currentUser();

    const email = user.emailAddresses[0]?.emailAddress;

    // The data is hardcoded for demonstration purposes
    const allEvents = [
      {
        year: 2009,
        week: 4,
        date: "2009-01-28",
        type: "personal",
        title: "Learned to Tie Shoelaces",
        description: "Mastered tying shoes without help",
        icon: "Users",
        color: "from-rose-500 to-rose-600",
        createdBy: email,
      },
      {
        year: 2009,
        week: 18,
        date: "2009-05-06",
        type: "travel",
        title: "First Train Ride",
        description: "Traveled to hometown during summer holidays",
        icon: "Plane",
        color: "from-cyan-500 to-cyan-600",
        createdBy: email,
      },
      {
        year: 2009,
        week: 26,
        date: "2009-06-29",
        type: "milestone",
        title: "Won Drawing Contest",
        description: "Awarded for creativity in local art competition",
        icon: "Award",
        color: "from-purple-500 to-purple-600",
        createdBy: email,
      },
      {
        year: 2009,
        week: 36,
        date: "2009-09-03",
        type: "global",
        title: "WhatsApp Founded",
        description: "Major messaging platform idea launched globally",
        icon: "Globe",
        color: "from-amber-500 to-amber-600",
        createdBy: email,
      },
      {
        year: 2009,
        week: 45,
        date: "2009-11-06",
        type: "career",
        title: "Curiosity About Robots",
        description: "Watched robot-themed cartoon that sparked tech curiosity",
        icon: "Briefcase",
        color: "from-emerald-500 to-emerald-600",
        createdBy: email,
      },
      {
        year: 2010,
        week: 5,
        date: "2010-02-03",
        type: "personal",
        title: "Learned to Write Full Sentences",
        description:
          "Started forming full sentences and expressing thoughts clearly",
        icon: "Users",
        color: "from-rose-500 to-rose-600",
        createdBy: email,
      },
      {
        year: 2010,
        week: 17,
        date: "2010-04-28",
        type: "travel",
        title: "First Zoo Visit",
        description: "Saw tigers, elephants, and exotic birds at the city zoo",
        icon: "Plane",
        color: "from-cyan-500 to-cyan-600",
        createdBy: email,
      },
      {
        year: 2010,
        week: 30,
        date: "2010-07-26",
        type: "milestone",
        title: "First Stage Performance",
        description: "Participated in school play and received applause",
        icon: "Award",
        color: "from-purple-500 to-purple-600",
        createdBy: email,
      },
      {
        year: 2010,
        week: 40,
        date: "2010-10-06",
        type: "global",
        title: "Instagram Launched",
        description:
          "New app launched, changing the way photos are shared online",
        icon: "Globe",
        color: "from-amber-500 to-amber-600",
        createdBy: email,
      },
      {
        year: 2010,
        week: 47,
        date: "2010-11-26",
        type: "career",
        title: "First Use of Computer",
        description: "Explored games and typing basics in school lab",
        icon: "Briefcase",
        color: "from-emerald-500 to-emerald-600",
        createdBy: email,
      },
      {
        year: 2011,
        week: 7,
        date: "2011-02-16",
        type: "personal",
        title: "Won Spelling Bee",
        description: "Secured 1st position in school spelling competition",
        icon: "Users",
        color: "from-rose-500 to-rose-600",
        createdBy: email,
      },
      {
        year: 2011,
        week: 18,
        date: "2011-05-04",
        type: "travel",
        title: "Trip to Delhi",
        description: "Visited historical monuments and museums",
        icon: "Plane",
        color: "from-cyan-500 to-cyan-600",
        createdBy: email,
      },
      {
        year: 2011,
        week: 27,
        date: "2011-07-07",
        type: "milestone",
        title: "Learned Swimming",
        description: "Completed beginner swimming course at local club",
        icon: "Award",
        color: "from-purple-500 to-purple-600",
        createdBy: email,
      },
      {
        year: 2011,
        week: 37,
        date: "2011-09-15",
        type: "global",
        title: "Steve Jobs Resigns from Apple",
        description: "Followed major tech news and leadership change",
        icon: "Globe",
        color: "from-amber-500 to-amber-600",
        createdBy: email,
      },
      {
        year: 2011,
        week: 44,
        date: "2011-11-05",
        type: "career",
        title: "Started Blogging",
        description: "Created a basic tech blog to share ideas and interests",
        icon: "Briefcase",
        color: "from-emerald-500 to-emerald-600",
        createdBy: email,
      },
      {
        year: 2012,
        week: 6,
        date: "2012-02-08",
        type: "personal",
        title: "Learned to Ride a Bicycle",
        description: "Took off training wheels and rode independently",
        icon: "Users",
        color: "from-rose-500 to-rose-600",
        createdBy: email,
      },
      {
        year: 2012,
        week: 20,
        date: "2012-05-16",
        type: "travel",
        title: "Trip to Kerala",
        description: "Experienced houseboats and backwaters during summer",
        icon: "Plane",
        color: "from-cyan-500 to-cyan-600",
        createdBy: email,
      },
      {
        year: 2012,
        week: 30,
        date: "2012-07-26",
        type: "milestone",
        title: "School Topper in Science",
        description: "Recognized as best performer in science stream",
        icon: "Award",
        color: "from-purple-500 to-purple-600",
        createdBy: email,
      },
      {
        year: 2012,
        week: 36,
        date: "2012-09-05",
        type: "global",
        title: "Curiosity Rover on Mars",
        description: "NASA's rover landing inspired interest in space",
        icon: "Globe",
        color: "from-amber-500 to-amber-600",
        createdBy: email,
      },
      {
        year: 2012,
        week: 47,
        date: "2012-11-21",
        type: "career",
        title: "First Career Fair Visit",
        description: "Visited a STEM fair and explored future paths",
        icon: "Briefcase",
        color: "from-emerald-500 to-emerald-600",
        createdBy: email,
      },
      {
        year: 2013,
        week: 5,
        date: "2013-01-30",
        type: "personal",
        title: "Joined Drama Club",
        description: "Participated in first school stage play",
        icon: "Users",
        color: "from-rose-500 to-rose-600",
        createdBy: email,
      },
      {
        year: 2013,
        week: 17,
        date: "2013-04-25",
        type: "travel",
        title: "Family Trip to Goa",
        description:
          "First beach holiday, collected seashells and built sandcastles",
        icon: "Plane",
        color: "from-cyan-500 to-cyan-600",
        createdBy: email,
      },
      {
        year: 2013,
        week: 29,
        date: "2013-07-20",
        type: "milestone",
        title: "School Rank Achievement",
        description: "Ranked in top 5% of class in annual exams",
        icon: "Award",
        color: "from-purple-500 to-purple-600",
        createdBy: email,
      },
      {
        year: 2013,
        week: 41,
        date: "2013-10-10",
        type: "career",
        title: "Explored Robotics",
        description: "Built a simple robot at a science camp",
        icon: "Briefcase",
        color: "from-emerald-500 to-emerald-600",
        createdBy: email,
      },
      {
        year: 2013,
        week: 46,
        date: "2013-11-17",
        type: "global",
        title: "Typhoon Haiyan",
        description:
          "Heard global news about devastating typhoon in the Philippines",
        icon: "Globe",
        color: "from-amber-500 to-amber-600",
        createdBy: email,
      },
      {
        year: 2014,
        week: 4,
        date: "2014-01-25",
        type: "milestone",
        title: "First Coding Class",
        description:
          "Attended first after-school programming class using Scratch",
        icon: "Award",
        color: "from-purple-500 to-purple-600",
        createdBy: email,
      },
      {
        year: 2014,
        week: 13,
        date: "2014-03-28",
        type: "personal",
        title: "Won Art Competition",
        description: "Secured 1st place in school-level painting contest",
        icon: "Users",
        color: "from-rose-500 to-rose-600",
        createdBy: email,
      },
      {
        year: 2014,
        week: 21,
        date: "2014-05-23",
        type: "travel",
        title: "Trip to Shimla",
        description: "Summer vacation in the hills with family",
        icon: "Plane",
        color: "from-cyan-500 to-cyan-600",
        createdBy: email,
      },
      {
        year: 2014,
        week: 39,
        date: "2014-09-27",
        type: "global",
        title: "Mars Orbiter Mission Success",
        description: "ISRO's MOM enters Mars orbit – national pride moment",
        icon: "Globe",
        color: "from-amber-500 to-amber-600",
        createdBy: email,
      },
      {
        year: 2014,
        week: 50,
        date: "2014-12-15",
        type: "career",
        title: "Curiosity Sparked",
        description:
          "Decided to become an engineer after a school science fair",
        icon: "Briefcase",
        color: "from-emerald-500 to-emerald-600",
        createdBy: email,
      },
      {
        year: 2016,
        week: 2,
        date: "2016-01-12",
        type: "milestone",
        title: "Built First Website",
        description: "Created a basic HTML portfolio as a beginner project",
        icon: "Award",
        color: "from-purple-500 to-purple-600",
        createdBy: email,
      },
      {
        year: 2016,
        week: 8,
        date: "2016-02-22",
        type: "personal",
        title: "Started Learning Guitar",
        description: "Took up guitar as a hobby and joined weekend classes",
        icon: "Users",
        color: "from-rose-500 to-rose-600",
        createdBy: email,
      },
      {
        year: 2016,
        week: 20,
        date: "2016-05-18",
        type: "career",
        title: "Completed Summer Tech Workshop",
        description: "Participated in hands-on programming bootcamp",
        icon: "Briefcase",
        color: "from-emerald-500 to-emerald-600",
        createdBy: email,
      },
      {
        year: 2016,
        week: 33,
        date: "2016-08-15",
        type: "travel",
        title: "Trip to Delhi & Agra",
        description: "Visited India Gate and Taj Mahal with family",
        icon: "Plane",
        color: "from-cyan-500 to-cyan-600",
        createdBy: email,
      },
      {
        year: 2016,
        week: 44,
        date: "2016-11-08",
        type: "global",
        title: "India Demonetization",
        description: "PM Modi announces demonetization of ₹500/₹1000 notes",
        icon: "Globe",
        color: "from-amber-500 to-amber-600",
        createdBy: email,
      },
      {
        year: 2017,
        week: 3,
        date: "2017-01-18",
        type: "personal",
        title: "Started Daily Journaling",
        description: "Began writing personal reflections and goals every day",
        icon: "Users",
        color: "from-rose-500 to-rose-600",
        createdBy: email,
      },
      {
        year: 2017,
        week: 12,
        date: "2017-03-22",
        type: "career",
        title: "First Technical Certification",
        description: "Completed a beginner course on Web Development",
        icon: "Briefcase",
        color: "from-emerald-500 to-emerald-600",
        createdBy: email,
      },
      {
        year: 2017,
        week: 24,
        date: "2017-06-15",
        type: "travel",
        title: "Trip to Kerala",
        description: "Visited Alleppey, Munnar and enjoyed houseboat stay",
        icon: "Plane",
        color: "from-cyan-500 to-cyan-600",
        createdBy: email,
      },
      {
        year: 2017,
        week: 36,
        date: "2017-09-06",
        type: "milestone",
        title: "Won School Coding Competition",
        description: "Built a quiz application using Java",
        icon: "Award",
        color: "from-purple-500 to-purple-600",
        createdBy: email,
      },
      {
        year: 2017,
        week: 48,
        date: "2017-12-01",
        type: "global",
        title: "Bitcoin Hits $19,000",
        description: "Witnessed global crypto frenzy and discussions",
        icon: "Globe",
        color: "from-amber-500 to-amber-600",
        createdBy: email,
      },
      {
        year: 2018,
        week: 5,
        date: "2018-02-01",
        type: "milestone",
        title: "Joined Coding Club",
        description: "Started contributing to open source and internal tools",
        icon: "Award",
        color: "from-purple-500 to-purple-600",
        createdBy: email,
      },
      {
        year: 2018,
        week: 14,
        date: "2018-04-06",
        type: "personal",
        title: "Hosted First Tech Meetup",
        description: "Organized an event for student developers",
        icon: "Users",
        color: "from-rose-500 to-rose-600",
        createdBy: email,
      },
      {
        year: 2018,
        week: 21,
        date: "2018-05-24",
        type: "career",
        title: "Mini Project Built with Java",
        description: "Library management system for college use",
        icon: "Briefcase",
        color: "from-emerald-500 to-emerald-600",
        createdBy: email,
      },
      {
        year: 2018,
        week: 33,
        date: "2018-08-13",
        type: "travel",
        title: "Trip to Andaman",
        description: "Scuba diving and remote island hopping",
        icon: "Plane",
        color: "from-cyan-500 to-cyan-600",
        createdBy: email,
      },
      {
        year: 2018,
        week: 47,
        date: "2018-11-23",
        type: "global",
        title: "Mars Insight Landing",
        description: "NASA lands probe on Mars to study its interior",
        icon: "Globe",
        color: "from-amber-500 to-amber-600",
        createdBy: email,
      },
      {
        year: 2019,
        week: 6,
        date: "2019-02-08",
        type: "career",
        title: "Campus Placement Prep Started",
        description: "Began solving DSA and mock interviews regularly",
        icon: "Briefcase",
        color: "from-emerald-500 to-emerald-600",
        createdBy: email,
      },
      {
        year: 2019,
        week: 17,
        date: "2019-04-25",
        type: "personal",
        title: "Joined Local Book Club",
        description: "Weekly reading and discussion sessions began",
        icon: "Users",
        color: "from-rose-500 to-rose-600",
        createdBy: email,
      },
      {
        year: 2019,
        week: 27,
        date: "2019-07-08",
        type: "travel",
        title: "North-East India Exploration",
        description: "Backpacking through Meghalaya and Sikkim",
        icon: "Plane",
        color: "from-cyan-500 to-cyan-600",
        createdBy: email,
      },
      {
        year: 2019,
        week: 35,
        date: "2019-09-01",
        type: "milestone",
        title: "Published First Blog Post",
        description: "Shared insights on learning Python online",
        icon: "Award",
        color: "from-purple-500 to-purple-600",
        createdBy: email,
      },
      {
        year: 2019,
        week: 49,
        date: "2019-12-09",
        type: "global",
        title: "Greta Thunberg at COP25",
        description: "Followed climate change activism highlights",
        icon: "Globe",
        color: "from-amber-500 to-amber-600",
        createdBy: email,
      },
      {
        year: 2020,
        week: 2,
        date: "2020-01-10",
        type: "milestone",
        title: "Completed 100 Days of Code",
        description: "Finished the challenge and built several projects",
        icon: "Award",
        color: "from-purple-500 to-purple-600",
        createdBy: email,
      },
      {
        year: 2020,
        week: 13,
        date: "2020-03-25",
        type: "global",
        title: "Nationwide Lockdown",
        description: "India entered lockdown during COVID-19 pandemic",
        icon: "Globe",
        color: "from-amber-500 to-amber-600",
        createdBy: email,
      },
      {
        year: 2020,
        week: 17,
        date: "2020-04-25",
        type: "career",
        title: "First Remote Internship",
        description: "Adapted to fully virtual work during pandemic",
        icon: "Briefcase",
        color: "from-emerald-500 to-emerald-600",
        createdBy: email,
      },
      {
        year: 2020,
        week: 27,
        date: "2020-07-05",
        type: "personal",
        title: "Learned to Cook",
        description: "Picked up cooking as a new lockdown hobby",
        icon: "Users",
        color: "from-rose-500 to-rose-600",
        createdBy: email,
      },
      {
        year: 2020,
        week: 40,
        date: "2020-10-01",
        type: "travel",
        title: "Virtual Museum Tours",
        description: "Explored Louvre, Vatican, and British Museum online",
        icon: "Plane",
        color: "from-cyan-500 to-cyan-600",
        createdBy: email,
      },
      {
        year: 2021,
        week: 3,
        date: "2021-01-15",
        type: "career",
        title: "Took Lead on Major Project",
        description:
          "Managed a cross-functional team delivering a new product feature",
        icon: "Briefcase",
        color: "from-emerald-500 to-emerald-600",
        createdBy: email,
      },
      {
        year: 2021,
        week: 11,
        date: "2021-03-15",
        type: "personal",
        title: "Adopted Healthy Diet",
        description: "Switched to a plant-based diet for better health",
        icon: "Users",
        color: "from-rose-500 to-rose-600",
        createdBy: email,
      },
      {
        year: 2021,
        week: 22,
        date: "2021-06-01",
        type: "travel",
        title: "Explored Kerala Backwaters",
        description: "Houseboat experience and cultural immersion",
        icon: "Plane",
        color: "from-cyan-500 to-cyan-600",
        createdBy: email,
      },
      {
        year: 2021,
        week: 34,
        date: "2021-08-25",
        type: "milestone",
        title: "Started Mentoring Juniors",
        description: "Began guiding college juniors in career prep",
        icon: "Award",
        color: "from-purple-500 to-purple-600",
        createdBy: email,
      },
      {
        year: 2021,
        week: 48,
        date: "2021-12-05",
        type: "global",
        title: "Omicron Variant Emerges",
        description: "Tracked global response to new COVID variant",
        icon: "Globe",
        color: "from-amber-500 to-amber-600",
        createdBy: email,
      },
      {
        year: 2022,
        week: 5,
        date: "2022-02-01",
        type: "career",
        title: "Joined Open Source Initiative",
        description: "Started contributing to Next.js and developer tools",
        icon: "Briefcase",
        color: "from-emerald-500 to-emerald-600",
        createdBy: email,
      },
      {
        year: 2022,
        week: 19,
        date: "2022-05-12",
        type: "travel",
        title: "Road Trip Across South India",
        description: "Covered over 1500 km in 2 weeks with friends",
        icon: "Plane",
        color: "from-cyan-500 to-cyan-600",
        createdBy: email,
      },
      {
        year: 2022,
        week: 27,
        date: "2022-07-10",
        type: "milestone",
        title: "Published First Technical Article",
        description: "Wrote about WebSockets on a tech blogging platform",
        icon: "Award",
        color: "from-purple-500 to-purple-600",
        createdBy: email,
      },
      {
        year: 2022,
        week: 38,
        date: "2022-09-19",
        type: "personal",
        title: "Started Journaling Habit",
        description: "Began journaling for mindfulness and self-awareness",
        icon: "Users",
        color: "from-rose-500 to-rose-600",
        createdBy: email,
      },
      {
        year: 2022,
        week: 45,
        date: "2022-11-09",
        type: "global",
        title: "Elections in Multiple Countries",
        description: "Followed global democratic elections closely",
        icon: "Globe",
        color: "from-amber-500 to-amber-600",
        createdBy: email,
      },
      {
        year: 2023,
        week: 4,
        date: "2023-01-27",
        type: "milestone",
        title: "Started Gym Routine",
        description: "Maintained consistent fitness routine for 6+ months",
        icon: "Award",
        color: "from-purple-500 to-purple-600",
        createdBy: email,
      },
      {
        year: 2023,
        week: 13,
        date: "2023-03-29",
        type: "career",
        title: "Hosted Internal Tech Workshop",
        description: "Taught juniors about REST APIs and TypeScript",
        icon: "Briefcase",
        color: "from-emerald-500 to-emerald-600",
        createdBy: email,
      },
      {
        year: 2023,
        week: 20,
        date: "2023-05-18",
        type: "personal",
        title: "Family Reunion",
        description: "Traveled home after 2 years for a big family gathering",
        icon: "Users",
        color: "from-rose-500 to-rose-600",
        createdBy: email,
      },
      {
        year: 2023,
        week: 33,
        date: "2023-08-16",
        type: "travel",
        title: "Himalayan Trek",
        description: "Summited Kedarkantha peak with a group of 10 trekkers",
        icon: "Plane",
        color: "from-cyan-500 to-cyan-600",
        createdBy: email,
      },
      {
        year: 2023,
        week: 46,
        date: "2023-11-20",
        type: "global",
        title: "Major AI Breakthrough",
        description: "Kept up with Gemini & GPT advancements in AI field",
        icon: "Globe",
        color: "from-amber-500 to-amber-600",
        createdBy: email,
      },
      {
        year: 2024,
        week: 6,
        date: "2024-02-07",
        type: "career",
        title: "Started New Role",
        description: "Joined AI startup as Full Stack Developer",
        icon: "Briefcase",
        color: "from-emerald-500 to-emerald-600",
        createdBy: email,
      },
      {
        year: 2024,
        week: 18,
        date: "2024-05-02",
        type: "travel",
        title: "Work Retreat in Bali",
        description: "Team-building trip to Bali with colleagues",
        icon: "Plane",
        color: "from-cyan-500 to-cyan-600",
        createdBy: email,
      },
      {
        year: 2024,
        week: 26,
        date: "2024-06-27",
        type: "milestone",
        title: "Graduated Postgraduate Program",
        description: "Completed Master's in Data Science",
        icon: "Award",
        color: "from-purple-500 to-purple-600",
        createdBy: email,
      },
      {
        year: 2024,
        week: 34,
        date: "2024-08-20",
        type: "personal",
        title: "Moved in with Friends",
        description: "Shifted to a new apartment with college buddies",
        icon: "Users",
        color: "from-rose-500 to-rose-600",
        createdBy: email,
      },
      {
        year: 2024,
        week: 47,
        date: "2024-11-22",
        type: "global",
        title: "Witnessed Global AI Summit",
        description: "Attended the International AI Conference virtually",
        icon: "Globe",
        color: "from-amber-500 to-amber-600",
        createdBy: email,
      },
      {
        year: 2025,
        week: 2,
        date: "2025-01-10",
        type: "milestone",
        title: "Launched First Product",
        description: "Deployed personal SaaS project to production",
        icon: "Award",
        color: "from-purple-500 to-purple-600",
        createdBy: email,
      },
      {
        year: 2025,
        week: 14,
        date: "2025-04-03",
        type: "career",
        title: "Promotion to Lead Engineer",
        description: "Took on leadership role in product team",
        icon: "Briefcase",
        color: "from-emerald-500 to-emerald-600",
        createdBy: email,
      },
      {
        year: 2025,
        week: 21,
        date: "2025-05-25",
        type: "travel",
        title: "Explored Northern Europe",
        description: "Visited Norway, Sweden, and Denmark",
        icon: "Plane",
        color: "from-cyan-500 to-cyan-600",
        createdBy: email,
      },
      {
        year: 2025,
        week: 36,
        date: "2025-09-03",
        type: "personal",
        title: "Adopted a Cat",
        description: "Welcomed Luna, a rescued kitten, into the family",
        icon: "Users",
        color: "from-rose-500 to-rose-600",
        createdBy: email,
      },
      {
        year: 2025,
        week: 48,
        date: "2025-11-27",
        type: "global",
        title: "Global Climate Agreement",
        description: "Followed historic international treaty on climate change",
        icon: "Globe",
        color: "from-amber-500 to-amber-600",
        createdBy: email,
      },
    ];

    const result = await db
      .insert(Events)
      .values(allEvents)
      .returning({ insertedId: Events.id });

    return NextResponse.json(result);
  } catch (error) {
    console.error("Error adding user to DB:", error);
    return NextResponse.json(
      { error: "Failed to add user to DB", userAdded: false, error: error },
      { status: 500 }
    );
  }
}
